/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testVoiture;

import NonAdmin.NonAdmin2;
import javaapplication2.applocation;
import javaapplication6.Creation;
import javaapplication6.Voiture;
import javaapplication6.modification;

/**
 *
 * @author SAMSUNG
 */
public class addVoiture extends javax.swing.JFrame {

    /**
     * Creates new form addVoiture
     */
    String type="";
    String mat;
    applocation a;
    NonAdmin2 ab ;
    
    public addVoiture() {
        initComponents();
    }
    public addVoiture(applocation aThis) {
                initComponents();
                a=aThis; 
                type="creation";     
                DispoField.setText("disponibile");
    }
    public addVoiture(NonAdmin2 aThis) {
                initComponents();
                ab=aThis; 
                type="creation";     
                DispoField.setText("disponibile");
    }
     public addVoiture(applocation aThis,Voiture r) {
                initComponents();
                type="modification";
                a=aThis;     
                MatriculeField.setText(r.getMatricule());
                MarqueField.setSelectedItem(r.getMarque());
                TypeField.setSelectedItem(r.getType());
                DispoField.setText(r.getDisponibilite());
                PrixField.setText(String.valueOf(r.getPrix()));
                mat=r.getMatricule();
                
           }
    public addVoiture(NonAdmin2 aThis,Voiture r) {
                initComponents();
                type="modification";
                ab=aThis;     
                MatriculeField.setText(r.getMatricule());
                MarqueField.setSelectedItem(r.getMarque());
                TypeField.setSelectedItem(r.getType());
                DispoField.setText(r.getDisponibilite());
                PrixField.setText(String.valueOf(r.getPrix()));
                mat=r.getMatricule();
                
           }
    
    
    
       public void modifierVoiture() {
           
                Voiture r=new Voiture();		
                r.setMatricule(MatriculeField.getText());
                r.setMarque(String.valueOf(MarqueField.getSelectedItem()));
                r.setType(String.valueOf(TypeField.getSelectedItem()));
                r.setDisponibilite(String.valueOf(DispoField.getText()));
                r.setPrix(Double.parseDouble(PrixField.getText()));
                r.setSiegeBebe("sans");
                modification c = new modification(r,this.mat);
           
                                         }
	public void inscrireVoiture() 
	{
                Voiture r = new Voiture();
                r.setMatricule(MatriculeField.getText());
                r.setMarque(String.valueOf(MarqueField.getSelectedItem()));
                r.setType(String.valueOf(TypeField.getSelectedItem()));
                r.setDisponibilite(String.valueOf(DispoField.getText()));
                r.setPrix(Double.parseDouble(PrixField.getText()));
                r.setSiegeBebe("sans");
                Creation c = new Creation(r);
	}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrixField = new javaapplication2.Customjtextfield();
        DispoField = new javaapplication2.Customjtextfield();
        TypeField = new javax.swing.JComboBox();
        MarqueField = new javax.swing.JComboBox();
        MatriculeField = new javaapplication2.Customjtextfield();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 576));
        setResizable(false);
        getContentPane().setLayout(null);

        PrixField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(PrixField);
        PrixField.setBounds(420, 350, 220, 30);

        DispoField.setForeground(new java.awt.Color(255, 255, 255));
        DispoField.setEnabled(false);
        getContentPane().add(DispoField);
        DispoField.setBounds(420, 290, 220, 30);

        TypeField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Essence", "Diesel" }));
        getContentPane().add(TypeField);
        TypeField.setBounds(420, 240, 220, 30);

        MarqueField.setMaximumRowCount(10);
        MarqueField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Renault", "Dacia", "Peugeot", "Citroen", "Fiat", "Ford", "Hyundai", "Kia", "Suzuki" }));
        getContentPane().add(MarqueField);
        MarqueField.setBounds(420, 180, 220, 30);

        MatriculeField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(MatriculeField);
        MatriculeField.setBounds(420, 120, 220, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testVoiture/fermer.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(870, 0, 30, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testVoiture/reduire.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(840, 0, 30, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testVoiture/barre.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 29);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testVoiture/submit-button.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(400, 430, 110, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testVoiture/Voiture.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        if(type.equals("creation")){
            inscrireVoiture();    
        }
         else{
            modifierVoiture();
                        }
            a.Update_Table_Voiture();                     

     this.dispose();

    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addVoiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addVoiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addVoiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addVoiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addVoiture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javaapplication2.Customjtextfield DispoField;
    private javax.swing.JComboBox MarqueField;
    private javaapplication2.Customjtextfield MatriculeField;
    private javaapplication2.Customjtextfield PrixField;
    private javax.swing.JComboBox TypeField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
