/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MpOublie;


import java.net.*;
import java.util.*; 
import javax.activation.*;
import javax.mail.*;
import javax.mail.internet.*;
import javax.naming.*;
import java.util.Properties;
import javaapplication6.Employe;
import javaapplication6.LoginFrame;
import static javaapplication6.trouver.trouverLogin;
import javax.swing.JOptionPane;


/**
 *
 * @author SAMSUNG
 */
public class MpOublie extends javax.swing.JFrame {
    
    LoginFrame a ;
    public MpOublie() {
        initComponents();
    }
    
    public MpOublie(LoginFrame aThis){
        initComponents();
        this.a=aThis ;
    }
    
    public static boolean sendMail(String from,String password, String message,String[] to){
		String host = "smtp.gmail.com";
		Properties props = new Properties();
                props.put("mail.smtp.auth","true");
		props.put("mail.smtp.starttls.enable", "true");
		props.put("mail.smtp.host",host);
		props.put("mail.smtp.user",from);
		props.put("mail.smtp.password",password);
		props.put("mail.smtp.port",587);
                Session session=Session.getDefaultInstance(props, null);
                MimeMessage mimeMessage = new MimeMessage(session);
                try {
                    mimeMessage.setFrom(new InternetAddress(from));
                    InternetAddress[] toAddress = new InternetAddress[to.length];
                    for (int i=0 ; i<to.length; i++){
                        toAddress[i]= new InternetAddress(to[i]);
                    }
                    for (int i=0 ; i<to.length; i++){
                        mimeMessage.addRecipient(Message.RecipientType.TO, toAddress[i]);
                    }
                    mimeMessage.setSubject("mail using javamail api");
                    mimeMessage.setText(message);
                    Transport transport=session.getTransport("smtp");
                    transport.connect(host,from,password);
                    transport.sendMessage(mimeMessage, mimeMessage.getAllRecipients());
                    transport.close();
                    return true ;
                    
                           
                        
                }catch(MessagingException me){
                    me.printStackTrace();
                }
		return false;
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmailField = new javaapplication2.Customjtextfield();
        LoginField = new javaapplication2.Customjtextfield();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 576));
        setMinimumSize(new java.awt.Dimension(900, 576));
        setPreferredSize(new java.awt.Dimension(900, 576));
        setResizable(false);
        getContentPane().setLayout(null);

        EmailField.setForeground(new java.awt.Color(255, 255, 255));
        EmailField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        getContentPane().add(EmailField);
        EmailField.setBounds(420, 270, 210, 30);

        LoginField.setForeground(new java.awt.Color(255, 255, 255));
        LoginField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        getContentPane().add(LoginField);
        LoginField.setBounds(420, 220, 210, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MpOublie/submit-button.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(410, 410, 100, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MpOublie/reduire.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(844, 0, 30, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MpOublie/fermer.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(870, 0, 30, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MpOublie/barre.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MpOublie/MpOublie.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 576);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Employe emp= trouverLogin(LoginField.getText());
        String[] to = {"arr.badr@gmail.com"};
        if (sendMail("agencelocationvoituremarrakech@gmail.com","ensa1234","message test",to))
            JOptionPane.showInputDialog(null, "Message envoyé");
        else 
            JOptionPane.showInputDialog(null, "Message non envoyé");
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MpOublie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MpOublie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MpOublie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MpOublie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MpOublie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javaapplication2.Customjtextfield EmailField;
    private javaapplication2.Customjtextfield LoginField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
