/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NonAdmin;

import javaapplication2.*;
import Compte.Compte;
import TestResa.AddResa;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaapplication6.Client;
import javaapplication6.Facture;
import javaapplication6.LoginFrame;
import javaapplication6.Reservation;
import static javaapplication6.Suppression.SupprimerClient;
import static javaapplication6.Suppression.SupprimerFacture;
import static javaapplication6.Suppression.SupprimerResa;
import static javaapplication6.Suppression.SupprimerVoiture;
import javaapplication6.Voiture;
import static javaapplication6.trouver.*;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import testFacture.addFacture;
import testVoiture.addVoiture;
import testclient.AddClient;

/**
 *
 * @author SAMSUNG
 */
public final class NonAdmin2 extends javax.swing.JFrame {
        private int xmouse,ymouse;
        private String SearchType="Client";
        private String Pass;
        String us;
        
        
        public String getPass(){
            return this.Pass;
        }
        public void setPass(String c){
            this.Pass=c;
        }
    /**
     * Creates new form applocation
     */
    public NonAdmin2() {
        initComponents();

        Toolkit tool= Toolkit.getDefaultToolkit();
        Dimension dim=new Dimension(tool.getScreenSize());
        int height= (int) dim.getHeight();
        int width= (int) dim.getWidth();
        setSize(width,height);
        setLocation((width/2-getWidth()/2),(height/2-getHeight()/2));
        Update_Table_Client();
        searchField.setText("CIN");  

                            }
 public NonAdmin2(String s,String mp) {
        initComponents();

        Toolkit tool= Toolkit.getDefaultToolkit();
        Dimension dim=new Dimension(tool.getScreenSize());
        int height= (int) dim.getHeight();
        int width= (int) dim.getWidth();
        setSize(width,height);
        setLocation((width/2-getWidth()/2),(height/2-getHeight()/2));
        Update_Table_Client();
        searchField.setText("CIN");  
        userField.setText("User "+Character.toUpperCase(s.charAt(0))+s.substring(1));
        this.setPass(mp);
        this.us=s;
                            }
    
    
        public  final void Update_Table_Tarif(){
           FactureTab.setModel(DbUtils.resultSetToTableModel(afficherfacture()));
                                                 }
        public  final void Update_Table_Voiture(){
           jTable3.setModel(DbUtils.resultSetToTableModel(affichervoiture()));
                                                 } 
        public  final void Update_Table_Client() {
            try {
                ClientTab.setModel(DbUtils.resultSetToTableModel(afficherclient()));
            } catch (SQLException ex) {
                Logger.getLogger(NonAdmin2.class.getName()).log(Level.SEVERE, null, ex);
            }        
                                                    }
        public  final void Update_Table_Reservation(){
           ResaTab.setModel(DbUtils.resultSetToTableModel(afficherReservation()));
                                                         }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fermer2 = new javax.swing.JLabel();
        reduire2 = new javax.swing.JLabel();
        barre = new javax.swing.JLabel();
        deplacer2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        userField = new javaapplication2.Customjtextfield();
        searchField = new javaapplication2.Customjtextfield();
        searchLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        vPanel = new javax.swing.JPanel();
        clientPanel = new javax.swing.JPanel();
        addClient = new javax.swing.JLabel();
        setClient = new javax.swing.JLabel();
        delClient = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ClientTab = new javax.swing.JTable();
        reservationPanel = new javax.swing.JPanel();
        addRes = new javax.swing.JLabel();
        setRes = new javax.swing.JLabel();
        delRes = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ResaTab = new javax.swing.JTable();
        tarifPanel = new javax.swing.JPanel();
        addTar = new javax.swing.JLabel();
        setTar = new javax.swing.JLabel();
        delTar = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        FactureTab = new javax.swing.JTable();
        voiturePanel = new javax.swing.JPanel();
        addVoit = new javax.swing.JLabel();
        setVoit = new javax.swing.JLabel();
        delVoit = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        clientButton = new javax.swing.JLabel();
        employeButton = new javax.swing.JLabel();
        reservButton = new javax.swing.JLabel();
        tarifButton = new javax.swing.JLabel();
        voitureButton = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1280, 960));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fermer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/fermer.png"))); // NOI18N
        fermer2.setToolTipText("");
        fermer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fermer2MouseClicked(evt);
            }
        });
        getContentPane().add(fermer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 30, -1, -1));

        reduire2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/reduire.png"))); // NOI18N
        reduire2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reduire2MouseClicked(evt);
            }
        });
        getContentPane().add(reduire2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 30, -1, -1));

        barre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/barre.png"))); // NOI18N
        getContentPane().add(barre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        deplacer2.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        deplacer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deplacer2MousePressed(evt);
            }
        });
        deplacer2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                deplacer2MouseDragged(evt);
            }
        });
        getContentPane().add(deplacer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/Administrator-icon.png"))); // NOI18N
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 40, 50));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Compte");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 180, 50));

        userField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        userField.setForeground(new java.awt.Color(204, 204, 204));
        userField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userField.setFocusable(false);
        userField.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        userField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFieldActionPerformed(evt);
            }
        });
        getContentPane().add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 180, 50));

        searchField.setBorder(null);
        searchField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchField.setEnabled(false);
        searchField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        searchField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchFieldMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchFieldMouseEntered(evt);
            }
        });
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        getContentPane().add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 90, 160, 30));

        searchLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/search boxes1.png"))); // NOI18N
        searchLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchLabelMouseClicked(evt);
            }
        });
        getContentPane().add(searchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 80, -1, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 640));

        vPanel.setBackground(new java.awt.Color(255, 255, 255));
        vPanel.setMinimumSize(new java.awt.Dimension(1050, 654));
        vPanel.setOpaque(false);
        vPanel.setPreferredSize(new java.awt.Dimension(1050, 654));
        vPanel.setLayout(new java.awt.CardLayout());

        clientPanel.setBackground(new java.awt.Color(255, 255, 255));
        clientPanel.setMinimumSize(new java.awt.Dimension(850, 599));
        clientPanel.setPreferredSize(new java.awt.Dimension(880, 650));
        clientPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/add.png"))); // NOI18N
        addClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addClientMouseClicked(evt);
            }
        });
        clientPanel.add(addClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(988, 0, -1, 70));

        setClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/modifier.png"))); // NOI18N
        setClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setClientMouseClicked(evt);
            }
        });
        clientPanel.add(setClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(988, 71, -1, 70));

        delClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/delete (1).png"))); // NOI18N
        delClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delClientMouseClicked(evt);
            }
        });
        clientPanel.add(delClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(988, 142, -1, 70));

        jScrollPane2.setBorder(null);
        jScrollPane2.setOpaque(false);

        ClientTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(ClientTab);

        clientPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 650));

        vPanel.add(clientPanel, "card2");

        reservationPanel.setBackground(new java.awt.Color(255, 255, 255));
        reservationPanel.setMaximumSize(new java.awt.Dimension(875, 600));
        reservationPanel.setMinimumSize(new java.awt.Dimension(875, 600));
        reservationPanel.setPreferredSize(new java.awt.Dimension(880, 650));
        reservationPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addRes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/add.png"))); // NOI18N
        addRes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addResMouseClicked(evt);
            }
        });
        reservationPanel.add(addRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(988, 0, -1, 70));

        setRes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/modifier.png"))); // NOI18N
        setRes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setResMouseClicked(evt);
            }
        });
        reservationPanel.add(setRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(988, 71, -1, 70));

        delRes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/delete (1).png"))); // NOI18N
        delRes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delResMouseClicked(evt);
            }
        });
        reservationPanel.add(delRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(988, 142, -1, 70));

        jScrollPane5.setBorder(null);
        jScrollPane5.setOpaque(false);

        ResaTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(ResaTab);

        reservationPanel.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 650));

        vPanel.add(reservationPanel, "card2");

        tarifPanel.setBackground(new java.awt.Color(255, 255, 255));
        tarifPanel.setMinimumSize(new java.awt.Dimension(850, 599));
        tarifPanel.setPreferredSize(new java.awt.Dimension(880, 650));
        tarifPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addTar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/add.png"))); // NOI18N
        addTar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addTarMouseClicked(evt);
            }
        });
        tarifPanel.add(addTar, new org.netbeans.lib.awtextra.AbsoluteConstraints(988, 0, -1, 70));

        setTar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/modifier.png"))); // NOI18N
        setTar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setTarMouseClicked(evt);
            }
        });
        tarifPanel.add(setTar, new org.netbeans.lib.awtextra.AbsoluteConstraints(988, 71, -1, 70));

        delTar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/delete (1).png"))); // NOI18N
        delTar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delTarMouseClicked(evt);
            }
        });
        tarifPanel.add(delTar, new org.netbeans.lib.awtextra.AbsoluteConstraints(988, 142, -1, 70));

        jScrollPane4.setBorder(null);
        jScrollPane4.setOpaque(false);

        FactureTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(FactureTab);

        tarifPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 600));

        vPanel.add(tarifPanel, "card2");
        tarifPanel.getAccessibleContext().setAccessibleDescription("");

        voiturePanel.setBackground(new java.awt.Color(255, 255, 255));
        voiturePanel.setRequestFocusEnabled(false);
        voiturePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addVoit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/add.png"))); // NOI18N
        addVoit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addVoitMouseClicked(evt);
            }
        });
        voiturePanel.add(addVoit, new org.netbeans.lib.awtextra.AbsoluteConstraints(988, 0, -1, 70));

        setVoit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/modifier.png"))); // NOI18N
        setVoit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setVoitMouseClicked(evt);
            }
        });
        voiturePanel.add(setVoit, new org.netbeans.lib.awtextra.AbsoluteConstraints(988, 71, -1, 70));

        delVoit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/delete (1).png"))); // NOI18N
        delVoit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delVoitMouseClicked(evt);
            }
        });
        voiturePanel.add(delVoit, new org.netbeans.lib.awtextra.AbsoluteConstraints(988, 142, -1, 70));

        jScrollPane3.setBorder(null);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.setOpaque(false);
        jScrollPane3.setViewportView(jTable3);

        voiturePanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 650));

        vPanel.add(voiturePanel, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(vPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 1060, -1));

        clientButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/clientTaille.png"))); // NOI18N
        clientButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clientButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clientButtonMouseExited(evt);
            }
        });
        clientButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                clientButtonMouseMoved(evt);
            }
        });
        getContentPane().add(clientButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 190, 70));

        employeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/employe1Taille.png"))); // NOI18N
        employeButton.setLabelFor(employeButton);
        employeButton.setToolTipText("");
        employeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                employeButtonMouseExited(evt);
            }
        });
        employeButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                employeButtonMouseMoved(evt);
            }
        });
        getContentPane().add(employeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        reservButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/resaTaille.png"))); // NOI18N
        reservButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reservButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reservButtonMouseExited(evt);
            }
        });
        reservButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                reservButtonMouseMoved(evt);
            }
        });
        getContentPane().add(reservButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        tarifButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/MoTaille.png"))); // NOI18N
        tarifButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tarifButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tarifButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tarifButtonMouseExited(evt);
            }
        });
        tarifButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tarifButtonMouseMoved(evt);
            }
        });
        getContentPane().add(tarifButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        voitureButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/voiture1Taille.png"))); // NOI18N
        voitureButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voitureButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voitureButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                voitureButtonMouseExited(evt);
            }
        });
        voitureButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                voitureButtonMouseMoved(evt);
            }
        });
        getContentPane().add(voitureButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/Copie de fondo-gris.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 960));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeButtonMouseClicked
        searchField.setEnabled(false);   
        ImageIcon in=new ImageIcon(getClass().getResource("search boxes1.png")); 
        searchField.setText(null);
        searchLabel.setIcon(in);             
        vPanel.removeAll();
        vPanel.repaint();
        vPanel.revalidate();
        //adding panel
        vPanel.repaint();
        vPanel.revalidate();
         SearchType="Employe";
    }//GEN-LAST:event_employeButtonMouseClicked

    private void tarifButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tarifButtonMouseClicked
        searchField.setEnabled(false);   
        ImageIcon in=new ImageIcon(getClass().getResource("search boxes1.png")); 
        searchLabel.setIcon(in);   
        searchField.setText("NumFacture");
        vPanel.removeAll();
        vPanel.repaint();
        vPanel.revalidate();
        //adding panel
        vPanel.add(tarifPanel);
        vPanel.repaint();
        vPanel.revalidate();
        Update_Table_Tarif();
        SearchType="Tarif";

    }//GEN-LAST:event_tarifButtonMouseClicked

    private void clientButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientButtonMouseClicked
        searchField.setEnabled(false);   
        ImageIcon in=new ImageIcon(getClass().getResource("search boxes1.png")); 
        searchLabel.setIcon(in); 
        searchField.setText("CIN");

        vPanel.removeAll();
        vPanel.repaint();
        vPanel.revalidate();
        
        //adding panel
        vPanel.add(clientPanel);
        vPanel.repaint();
        vPanel.revalidate();
        Update_Table_Client();
        SearchType="Client";

    }//GEN-LAST:event_clientButtonMouseClicked

    private void reservButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservButtonMouseClicked
        searchField.setEnabled(false);   
        ImageIcon in=new ImageIcon(getClass().getResource("search boxes1.png")); 
        searchLabel.setIcon(in);     
        searchField.setText("NumReserv");

        vPanel.removeAll();
        vPanel.repaint();
        vPanel.revalidate();
        
        //adding panel
        vPanel.add(reservationPanel);
        vPanel.repaint();
        vPanel.revalidate();
        Update_Table_Reservation();
        SearchType="Reservation";

    }//GEN-LAST:event_reservButtonMouseClicked

    private void clientButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientButtonMouseMoved
        ImageIcon in= new ImageIcon(getClass().getResource("clientTaillel.png"));
        clientButton.setIcon(in);
    }//GEN-LAST:event_clientButtonMouseMoved

    private void employeButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeButtonMouseMoved
        
        ImageIcon n= new ImageIcon(getClass().getResource("employe1Taillel.png"));
        employeButton.setIcon(n);
    }//GEN-LAST:event_employeButtonMouseMoved

    private void reservButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservButtonMouseMoved
       
        ImageIcon n= new ImageIcon(getClass().getResource("resaTaillel.png"));
        reservButton.setIcon(n);
    }//GEN-LAST:event_reservButtonMouseMoved

    private void tarifButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tarifButtonMouseMoved
        
        ImageIcon n= new ImageIcon(getClass().getResource("MoTaillel.png"));
        tarifButton.setIcon(n);
    }//GEN-LAST:event_tarifButtonMouseMoved

    private void clientButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientButtonMouseExited
       
        ImageIcon in= new ImageIcon(getClass().getResource("clientTaille.png"));
        clientButton.setIcon(in);
    }//GEN-LAST:event_clientButtonMouseExited

    private void employeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeButtonMouseExited
      
        ImageIcon n= new ImageIcon(getClass().getResource("employe1Taille.png"));
        employeButton.setIcon(n);
    }//GEN-LAST:event_employeButtonMouseExited

    private void reservButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservButtonMouseExited
        
        ImageIcon n= new ImageIcon(getClass().getResource("resaTaille.png"));
        reservButton.setIcon(n);
    }//GEN-LAST:event_reservButtonMouseExited

    private void tarifButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tarifButtonMouseExited
      
        ImageIcon n= new ImageIcon(getClass().getResource("MoTaille.png"));
        tarifButton.setIcon(n);
    }//GEN-LAST:event_tarifButtonMouseExited

    private void reduire2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reduire2MouseClicked
             this.setState(NonAdmin2.ICONIFIED);        
    }//GEN-LAST:event_reduire2MouseClicked

    private void deplacer2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deplacer2MousePressed
        ymouse=evt.getY();
        xmouse=evt.getX();       
    }//GEN-LAST:event_deplacer2MousePressed

    private void deplacer2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deplacer2MouseDragged
          int x=evt.getXOnScreen();
            int y=evt.getYOnScreen();
            this.setLocation(x-xmouse, y-ymouse);
           
    }//GEN-LAST:event_deplacer2MouseDragged

    private void voitureButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voitureButtonMouseMoved
       
        ImageIcon n= new ImageIcon(getClass().getResource("voiture1Taillel.png"));
        voitureButton.setIcon(n);

    }//GEN-LAST:event_voitureButtonMouseMoved

    private void voitureButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voitureButtonMouseExited
        
        ImageIcon n= new ImageIcon(getClass().getResource("voiture1Taille.png"));
        voitureButton.setIcon(n);
    }//GEN-LAST:event_voitureButtonMouseExited

    private void voitureButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voitureButtonMouseClicked
       searchField.setText("Matricule");
       Update_Table_Voiture();
       searchField.setEnabled(false);   
        ImageIcon in=new ImageIcon(getClass().getResource("search boxes1.png")); 
        searchLabel.setIcon(in);     
       vPanel.removeAll();
       vPanel.repaint();
       vPanel.revalidate();
       //adding panel
       vPanel.add(voiturePanel);
       vPanel.repaint();
       vPanel.revalidate();
    }//GEN-LAST:event_voitureButtonMouseClicked

    private void searchLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchLabelMouseClicked
       if(SearchType.equals("Client")){
         ClientTab.setModel(DbUtils.resultSetToTableModel(trouverCinClient(searchField.getText())));
       }
       if(SearchType.equals("Tarif")){
          FactureTab.setModel(DbUtils.resultSetToTableModel(trouverFactureR(Integer.parseInt(searchField.getText()))));

       }
       
        if(SearchType.equals("Reservation")){
          ResaTab.setModel(DbUtils.resultSetToTableModel(trouveNumResaR(Integer.parseInt(searchField.getText()))));

       }
       
            
        searchField.setEnabled(false); 
        searchField.setText(null);
        ImageIcon in=new ImageIcon(getClass().getResource("search boxes1.png")); 
        searchLabel.setIcon(in);  
        
    }//GEN-LAST:event_searchLabelMouseClicked

    private void searchFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchFieldMouseClicked
      searchField.setText(null);  
      
       
      
      
    }//GEN-LAST:event_searchFieldMouseClicked

    private void searchFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchFieldMouseEntered
      searchField.setEnabled(true);  
      ImageIcon in=new ImageIcon(getClass().getResource("search boxes.png")); 
      searchLabel.setIcon(in); 
           }//GEN-LAST:event_searchFieldMouseEntered

    private void delVoitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delVoitMouseClicked
        String n=JOptionPane.showInputDialog(null,"Attention la suppresion est irreversible ! \nSi vous êtes sur entrez le  num de matricule a suprimmer","suprimmer une voiture",JOptionPane.WARNING_MESSAGE);        // TODO add your handling code here:
        SupprimerVoiture(n);  
        Update_Table_Voiture();    
    }//GEN-LAST:event_delVoitMouseClicked

    private void delClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delClientMouseClicked
        String cin=JOptionPane.showInputDialog(null,"Attention la suppresion est irreversible ! \nSi vous êtes sur entrez le  CIN du client a suprimmer","suprimmer un client",JOptionPane.WARNING_MESSAGE);        // TODO add your handling code here:
        SupprimerClient(cin);  
        Update_Table_Client();


// TODO add your handling code here:
    }//GEN-LAST:event_delClientMouseClicked

    private void addClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addClientMouseClicked
          new AddClient(this).setVisible(true);  
    }//GEN-LAST:event_addClientMouseClicked

    private void setClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setClientMouseClicked
     String cin=JOptionPane.showInputDialog(null,"Attention la modification est irreversible ! \nSi vous êtes sur entrez le  CIN du client a modifier","modifier un client",JOptionPane.WARNING_MESSAGE);        
      Client client=new Client();
      client=trouverCinClient2(cin);
     new AddClient(this,client).setVisible(true);
    }//GEN-LAST:event_setClientMouseClicked

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void addResMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addResMouseClicked
             new AddResa(this).setVisible(true);
    }//GEN-LAST:event_addResMouseClicked

    private void setResMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setResMouseClicked
        int numRes=Integer.parseInt(JOptionPane.showInputDialog(null, "Attention la modification est irreversible ! \nSi vous êtes sur entrez le  num de reservation a modifier",JOptionPane.WARNING_MESSAGE));
        Reservation r=new Reservation();
        r=trouveNumResa(numRes);
        new AddResa(this,r).setVisible(true);

       }//GEN-LAST:event_setResMouseClicked

    private void delResMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delResMouseClicked
        // TODO add your handling code here:
        int n=Integer.parseInt(JOptionPane.showInputDialog(null,"Attention la suppresion est irreversible ! \nSi vous êtes sur entrez le  num de la reservation a suprimmer","suprimmer une reservation",JOptionPane.WARNING_MESSAGE)); 
        SupprimerResa(n);  
        Update_Table_Reservation();
    }//GEN-LAST:event_delResMouseClicked

    private void addVoitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVoitMouseClicked
        new addVoiture(this).setVisible(true);
    }//GEN-LAST:event_addVoitMouseClicked

    private void addTarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTarMouseClicked
         new addFacture(this).setVisible(true);  


    }//GEN-LAST:event_addTarMouseClicked

    private void setTarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setTarMouseClicked
        int n=Integer.parseInt(JOptionPane.showInputDialog(null,"Attention la modification est irreversible ! \nSi vous êtes sur entrez le  num de la facture a modifier","modifier une facture",JOptionPane.WARNING_MESSAGE));        // TODO add your handling code here:
        Facture f = new Facture() ;
        f = trouverFacture(n);
        if (f.getMontant() != 0)
            new addFacture(this,f).setVisible(true);

    }//GEN-LAST:event_setTarMouseClicked

    private void delTarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delTarMouseClicked

        int n=Integer.parseInt(JOptionPane.showInputDialog(null,"Attention la suppresion est irreversible ! \nSi vous êtes sur entrez le  num de la facture a suprimmer","suprimmer une reservation",JOptionPane.WARNING_MESSAGE));        // TODO add your handling code here:
        SupprimerFacture(n);  
        Update_Table_Tarif();

    }//GEN-LAST:event_delTarMouseClicked

    private void userFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userFieldActionPerformed

    private void fermer2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermer2MouseClicked
        this.dispose(); 
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_fermer2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
      new Compte(this,this.us).setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void setVoitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setVoitMouseClicked
        String mat = String.valueOf(JOptionPane.showInputDialog(null, "Attention la modification est irreversible ! \nSi vous êtes sur entrez le  num de matricule a modifier",JOptionPane.WARNING_MESSAGE));
        Voiture r=new Voiture();
        r= trouverVoiture(mat);
        new addVoiture(this,r).setVisible(true);

    }//GEN-LAST:event_setVoitMouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NonAdmin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NonAdmin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NonAdmin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NonAdmin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NonAdmin2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ClientTab;
    private javax.swing.JTable FactureTab;
    private javax.swing.JTable ResaTab;
    private javax.swing.JLabel addClient;
    private javax.swing.JLabel addRes;
    private javax.swing.JLabel addTar;
    private javax.swing.JLabel addVoit;
    private javax.swing.JLabel barre;
    private javax.swing.JLabel clientButton;
    private javax.swing.JPanel clientPanel;
    private javax.swing.JLabel delClient;
    private javax.swing.JLabel delRes;
    private javax.swing.JLabel delTar;
    private javax.swing.JLabel delVoit;
    private javax.swing.JLabel deplacer2;
    private javax.swing.JLabel employeButton;
    private javax.swing.JLabel fermer2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel reduire2;
    private javax.swing.JLabel reservButton;
    private javax.swing.JPanel reservationPanel;
    private javaapplication2.Customjtextfield searchField;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JLabel setClient;
    private javax.swing.JLabel setRes;
    private javax.swing.JLabel setTar;
    private javax.swing.JLabel setVoit;
    private javax.swing.JLabel tarifButton;
    private javax.swing.JPanel tarifPanel;
    private javaapplication2.Customjtextfield userField;
    private javax.swing.JPanel vPanel;
    private javax.swing.JLabel voitureButton;
    private javax.swing.JPanel voiturePanel;
    // End of variables declaration//GEN-END:variables
}
