/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NouveauEmp;

import javaapplication2.applocation;
import javaapplication6.Creation;
import javaapplication6.Employe;
import javaapplication6.LoginFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author SAMSUNG
 */
public class NouveauEmp extends javax.swing.JFrame {

    /**
     * Creates new form NouveauEmp
     * 
     */
    LoginFrame a ;
    public NouveauEmp() {
        initComponents();
    }
    
    
    public NouveauEmp(LoginFrame aThis){
        initComponents();
        a=aThis;
    }
    
    public boolean Reponse(){
        if ( !MpField.getText().equals(RetaperMpField.getText()))
            return false;
        else 
            return true;
    }
    public void InscrireEmp(){
        Employe e = new Employe();
        e.setNom(NomField.getText());
        e.setPrenom(PrenomField.getText());
        e.setPhone(PhoneField.getText());
        e.setUserName(LoginField.getText());
        e.setEmail(EmailField.getText());
        e.setPassword(MpField.getText());
        e.setCompte("desactive");
        Creation emp = new Creation(e);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomField = new javaapplication2.Customjtextfield();
        PrenomField = new javaapplication2.Customjtextfield();
        PhoneField = new javaapplication2.Customjtextfield();
        LoginField = new javaapplication2.Customjtextfield();
        EmailField = new javaapplication2.Customjtextfield();
        MpField = new javax.swing.JPasswordField();
        RetaperMpField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 576));
        setMinimumSize(new java.awt.Dimension(900, 576));
        setPreferredSize(new java.awt.Dimension(900, 576));
        setResizable(false);
        getContentPane().setLayout(null);

        NomField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(NomField);
        NomField.setBounds(450, 120, 200, 30);

        PrenomField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(PrenomField);
        PrenomField.setBounds(450, 160, 200, 30);

        PhoneField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(PhoneField);
        PhoneField.setBounds(450, 200, 200, 30);

        LoginField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(LoginField);
        LoginField.setBounds(450, 240, 200, 30);

        EmailField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(EmailField);
        EmailField.setBounds(450, 280, 200, 30);
        getContentPane().add(MpField);
        MpField.setBounds(450, 320, 200, 30);
        getContentPane().add(RetaperMpField);
        RetaperMpField.setBounds(450, 370, 200, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NouveauEmp/fermer.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(870, 0, 34, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NouveauEmp/reduire.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(840, 0, 34, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NouveauEmp/barre.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 29);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NouveauEmp/submit-button.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(400, 450, 110, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NouveauEmp/Employé Création.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        if (Reponse()){
            InscrireEmp();
            this.dispose();
        }
        else 
            JOptionPane.showMessageDialog(null,"Les deux champs de mot de passe sont différents. Réessayer !");
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NouveauEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NouveauEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NouveauEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NouveauEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NouveauEmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javaapplication2.Customjtextfield EmailField;
    private javaapplication2.Customjtextfield LoginField;
    private javax.swing.JPasswordField MpField;
    private javaapplication2.Customjtextfield NomField;
    private javaapplication2.Customjtextfield PhoneField;
    private javaapplication2.Customjtextfield PrenomField;
    private javax.swing.JPasswordField RetaperMpField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
