/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testclient;

import NonAdmin.NonAdmin2;
import java.sql.Date;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaapplication6.Client;
import javaapplication6.Creation;
import javax.swing.ImageIcon;
import javaapplication6.*;
import javaapplication2.applocation;
import javaapplication2.*;

import static javaapplication6.trouver.afficherclient;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author choaib
 */
public class AddClient extends javax.swing.JFrame  {
        
    /**
     * Creates new form NewJFrame
     */
    String type="";
    String cin="";
    applocation a;
    NonAdmin2 ab ;
    public AddClient() {
        initComponents();
    }
        
    public AddClient(applocation aThis) {
                initComponents();
                a=aThis; 
                type="creation";
                                }
    public AddClient(NonAdmin2 aThis) {
                initComponents();
                ab=aThis; 
                type="creation";
                                }
    public AddClient(NonAdmin2 aThis,Client client) {
               
                type="modification";
                initComponents();
                ab=aThis;     
                NameField.setText(client.getNom());
                PrenomField.setText(client.getPrenom());
                CinField.setText(client.getCIN());
                AdresseField.setText(client.getAdresse());
                DateField.setDate(client.getDateNaissance());
                PhoneField.setText(client.getPhone());
                NationaliteField.setSelectedItem(client.getNationalite());
               
                //DateField.setText(String.valueOf(client.getDateNaissance()));
                cin=client.getCIN();
           }
    
    
     public AddClient(applocation aThis,Client client) {
               
                type="modification";
                initComponents();
                a=aThis;     
                NameField.setText(client.getNom());
                PrenomField.setText(client.getPrenom());
                CinField.setText(client.getCIN());
                AdresseField.setText(client.getAdresse());
                DateField.setDate(client.getDateNaissance());
                PhoneField.setText(client.getPhone());
                NationaliteField.setSelectedItem(client.getNationalite());
               
                //DateField.setText(String.valueOf(client.getDateNaissance()));
                cin=client.getCIN();
           }
    
    
    
       public void modifierClient() {
           
                 Client client=new Client();
		
		
		client.setNom(NameField.getText());
		client.setPrenom(PrenomField.getText());
		client.setCIN(CinField.getText());
		client.setNationalite (String.valueOf( NationaliteField.getSelectedItem()));
                client.setPhone(PhoneField.getText());                   
		client.setAdresse(AdresseField.getText());
                java.util.Date utilDate = DateField.getDate();
                java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
                client.setDateNaissance(sqlDate);
                modification c=new modification(client,this.cin);
           
                                         }
	public void inscrireClient() 
	{       Client client=new Client();
		
		
		client.setNom(NameField.getText());
		client.setPrenom(PrenomField.getText());
                client.setNationalite((String) NationaliteField.getSelectedItem());
		client.setCIN(CinField.getText());
                client.setAdresse(AdresseField.getText()); 
                java.util.Date utilDate = DateField.getDate();
                java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
                client.setDateNaissance(sqlDate);           
                client.setPhone(PhoneField.getText());                  
                Creation c = new Creation(client);
	}
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameField = new javaapplication2.Customjtextfield();
        PrenomField = new javaapplication2.Customjtextfield();
        CinField = new javaapplication2.Customjtextfield();
        AdresseField = new javaapplication2.Customjtextfield();
        PhoneField = new javaapplication2.Customjtextfield();
        jLabel4 = new javax.swing.JLabel();
        DateField = new javaapplication6.jtest();
        NationaliteField = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 22, 770, 555));
        setMinimumSize(new java.awt.Dimension(770, 555));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 210, 30));

        PrenomField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(PrenomField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 210, 30));

        CinField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(CinField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 210, 30));

        AdresseField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(AdresseField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 270, 30));

        PhoneField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(PhoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 210, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testclient/fermer.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 30, 30));

        DateField.setBackground(new java.awt.Color(0, 0, 0));
        DateField.setForeground(new java.awt.Color(153, 153, 153));
        DateField.setDateFormatString("dd-MM-yyyy");
        DateField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        DateField.setOpaque(false);
        DateField.setRequestFocusEnabled(false);
        getContentPane().add(DateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 210, 30));

        NationaliteField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Marocaine", "Etrangère" }));
        getContentPane().add(NationaliteField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 210, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testclient/barre.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 900, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testclient/submit-button.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, -1, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testclient/Client.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, -1, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
         if(type.equals("creation")){
            inscrireClient();    }
         else{
            modifierClient();
                        }
   a.Update_Table_Client();                     

     this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved
        ImageIcon img=new ImageIcon(getClass().getResource("submit-buttonl.png"));
        jLabel2.setIcon(img);

    }//GEN-LAST:event_jLabel2MouseMoved

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
         ImageIcon img=new ImageIcon(getClass().getResource("submit-button.png"));
        jLabel2.setIcon(img);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javaapplication2.Customjtextfield AdresseField;
    private javaapplication2.Customjtextfield CinField;
    private javaapplication6.jtest DateField;
    private javaapplication2.Customjtextfield NameField;
    private javax.swing.JComboBox NationaliteField;
    private javaapplication2.Customjtextfield PhoneField;
    private javaapplication2.Customjtextfield PrenomField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
