/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Compte;

import ModifierEmp.ModifierEmp;
import NonAdmin.NonAdmin2;
import javaapplication2.applocation;
import javaapplication6.*;
import static javaapplication6.trouver.trouverEmp;

/**
 *
 * @author SAMSUNG
 */
public class Compte extends javax.swing.JFrame {

    applocation a ;
    String u ;
    String pass ;
    NonAdmin2 ab;
    
    
    public Compte(applocation aThis,String user){
        initComponents();
        this.a = aThis;
        this.u = user;
        Employe e = trouverEmp(user);
        NomField.setText(e.getNom());
        PrenomField.setText(e.getPrenom());
        PhoneField.setText(e.getPhone());
        LoginField.setText(e.getUserName());
        EmailField.setText(e.getEmail());
        this.pass=e.getPassword();
         
    }
    public Compte(NonAdmin2 aThis,String user){
        initComponents();
        this.ab = aThis;
        this.u = user;
        Employe e = trouverEmp(user);
        NomField.setText(e.getNom());
        PrenomField.setText(e.getPrenom());
        PhoneField.setText(e.getPhone());
        LoginField.setText(e.getUserName());
        EmailField.setText(e.getEmail());
        this.pass=e.getPassword();
         
    }
    /**
     * Creates new form Compte
     */
    public Compte() {
        initComponents();
    }
    
    
    public void SubmitEmp(){
        Employe e = trouverEmp(this.u);
        e.setNom(NomField.getText());
        e.setPrenom(PrenomField.getText());
        e.setPhone(PhoneField.getText());
        e.setUserName(LoginField.getText());
        e.setEmail(EmailField.getText());
        modification m = new modification(e,this.u);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmailField = new javaapplication2.Customjtextfield();
        NomField = new javaapplication2.Customjtextfield();
        PrenomField = new javaapplication2.Customjtextfield();
        PhoneField = new javaapplication2.Customjtextfield();
        LoginField = new javaapplication2.Customjtextfield();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 576));
        setMinimumSize(new java.awt.Dimension(900, 576));
        setPreferredSize(new java.awt.Dimension(900, 576));
        setResizable(false);
        getContentPane().setLayout(null);

        EmailField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(EmailField);
        EmailField.setBounds(440, 290, 200, 30);

        NomField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(NomField);
        NomField.setBounds(440, 130, 200, 30);

        PrenomField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(PrenomField);
        PrenomField.setBounds(440, 170, 200, 30);

        PhoneField.setForeground(new java.awt.Color(255, 255, 255));
        PhoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneFieldActionPerformed(evt);
            }
        });
        getContentPane().add(PhoneField);
        PhoneField.setBounds(440, 210, 200, 30);

        LoginField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(LoginField);
        LoginField.setBounds(440, 250, 200, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Compte/reduire.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(840, 0, 34, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Compte/fermer.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(870, 0, 34, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Compte/barre.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 30);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Modifier mot de passe");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 410, 210, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Compte/submit-button.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(530, 410, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Compte/Employé Compte.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        SubmitEmp();
        this.dispose();
        a.Update_Table_Employe();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        new ModifierEmp(this.a ,this,this.u).setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void PhoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Compte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javaapplication2.Customjtextfield EmailField;
    private javaapplication2.Customjtextfield LoginField;
    private javaapplication2.Customjtextfield NomField;
    private javaapplication2.Customjtextfield PhoneField;
    private javaapplication2.Customjtextfield PrenomField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
